apiVersion: apps/v1
kind: Deployment
metadata:
  name:  js-server
  namespace: default
  labels:
    app:  js-server
spec:
  selector:
    matchLabels:
      app: js-server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  js-server
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  js-server
        image:  perebaj/js-server:1.0.0
        ports:
        - containerPort:  8080
        