apiVersion: kuztomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - js-server-deployment.yaml
  - js-server-service.yaml

namespace: js-server

images:
- name: js-server
  newName: js-server